config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"

  resources :homes, only: [:index] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  include HomesHelper

  before_action :validate_search_params, only: :search

  def index
  end

  def search
    breed_name_formatted = breed_name_formatted(search_params[:query])

    response = HTTParty.get("https://dog.ceo/api/breed/#{breed_name_formatted}/images/random")

    if success_response?(response["status"])
      @image = response['message']
      render turbo_stream: [ turbo_stream.update('image_container',
                                                 partial: 'partials/image', locals: { image_url: @image,
                                                 breed_name: breed_name_formatted  })]
    elsif error_response?(response["status"])
      render_error(response["message"])
    else
      render_error('Internal server error...')
      redirect_to root_path
    end
  end

  private

  def validate_search_params
    if params[:search][:query].blank?
      render_error('Please enter a breed name to search for')
      return
    end
  end

  def render_error(error_message)
    render turbo_stream: turbo_stream.update('error_container',
                                              partial: 'partials/errors',
                                              locals: {
                                                  error_message: error_message
                                              })
  end

  def success_response?(status)
    status == "success".freeze
  end

  def error_response?(status)
    status == "error".freeze
  end

  def search_params
    params.require(:search).permit(:query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  # Format breed name for url with hyphens and makes it lowercase
  # example: "German Shepherd" => "german-shepherd"
  def breed_name_formatted(breed_name)
    breed_name.downcase.split.join('-')
  end
end

app/views/homes/index.html.erb
<%= render partial: 'partials/header' %>

<div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-lg text-center">
    <h1 class="text-2xl font-bold sm:text-3xl">Search Your favorite dog by Breed</h1>

    <p class="mt-4 text-gray-500">
      Search Via the Search Bar and Click the Button Below.
      Write the favorite dog breed name.
    </p>
  </div>

  <%= form_with(url: search_homes_path,  method: :get, data: { controller: "turbo-form" }, class: 'mx-auto mb-0 mt-8 max-w-md space-y-4') do |form| %>
    <div>
      <%= form.label 'search[query]', class: 'sr-only' %>
      <div class="relative">
        <%= form.text_field 'search[query]',
            placeholder: 'Breed',
            class: 'w-full rounded-lg border border-gray-400 p-4 pe-12 text-sm shadow-sm' %>
      </div>
    </div>


    <div class="flex items-center justify-between cursor-pointer">
      <%= form.submit 'Search', data: { turbo_frame: 'image_container', remote: true },
          class: 'cursor-pointer inline-block rounded-lg bg-blue-500 px-5 py-3 text-sm font-medium text-white' %>
    </div>
  <% end %>
</div>

<%= turbo_frame_tag 'image_container' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dog Breed Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <%= turbo_frame_tag 'error_container' %>
    <%= yield %>
  </body>
</html>

app/views/partial/_errors.html.erb
<div role="alert" class="rounded border-s-4 border-red-500 bg-red-50 p-4">
  <div class="flex items-center gap-2 text-red-800">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5">
      <path
        fill-rule="evenodd"
        d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 01.75.75v3.75a.75.75 0 01-1.5 0V9a.75.75 0 01.75-.75zm0 8.25a.75.75 0 100-1.5.75.75 0 000 1.5z"
        clip-rule="evenodd"
      />
    </svg>

    <strong class="block font-medium"> Something went wrong </strong>
  </div>

  <p class="mt-2 text-sm text-red-700">
    <%= error_message %>
  </p>
</div>

app/views/partial/_header.html.erb
<header>
  <div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="text-center sm:text-left">
        <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Dog Search</h1>

        <p class="mt-1.5 text-sm text-gray-500">Search your favorite Dog by Breed 🎉</p>
      </div>

      <div class="mt-4 flex flex-col gap-4 sm:mt-0 sm:flex-row sm:items-center">
        <button
          class="inline-flex items-center justify-center gap-1.5 rounded-lg border border-gray-200 px-5 py-3 text-gray-500 transition hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:ring"
          type="button"
        >
          <span class="text-sm font-medium"> Github Link </span>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
            />
          </svg>
        </button>

        <button
          class="block rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring"
          type="button"
        >
          Check React JS Version 
        </button>
      </div>
    </div>
  </div>
</header>

app/views/partials/_errors.html.erb
<div role="alert" class="rounded border-s-4 border-red-500 bg-red-50 p-4" id="error-alert">
  <div class="flex items-center gap-2 text-red-800">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5">
      <path
        fill-rule="evenodd"
        d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 01.75.75v3.75a.75.75 0 01-1.5 0V9a.75.75 0 01.75-.75zm0 8.25a.75.75 0 100-1.5.75.75 0 000 1.5z"
        clip-rule="evenodd"
      />
    </svg>

    <strong class="block font-medium"> Something went wrong </strong>
  </div>

  <p class="mt-2 text-sm text-red-700">
    <%= error_message %>
  </p>
</div>

app/views/partials/_header.html.erb
<header>
  <div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="text-center sm:text-left">
        <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Dog Search</h1>

        <p class="mt-1.5 text-sm text-gray-500">Search your favorite Dog by Breed 🎉</p>
      </div>

      <div class="mt-4 flex flex-col gap-4 sm:mt-0 sm:flex-row sm:items-center">
        <a href="https://github.com/prio101/dog_breed_search"
          target="_blank"
          class="inline-flex items-center justify-center gap-1.5 rounded-lg border border-gray-200 px-5 py-3 text-gray-500 transition hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:ring"
          type="button"
        >
          <span class="text-sm font-medium"> Github Link </span>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
            />
          </svg>
        </a>
      </div>
    </div>
  </div>
</header>

app/views/partials/_image.html.erb
<div class="w-full flex flex-1 justify-center items-center">
  <div class="m-10">

    <a href="#" class="group relative block bg-black">

      <img id="image"
          src="<%= image_url %>"
          alt="<%= breed_name %>-dog"
          class="absolute inset-0 h-full w-full object-cover opacity-75 transition-opacity group-hover:opacity-50">

      <div class="relative p-4 sm:p-6 lg:p-8">
        <p class="text-sm font-medium uppercase tracking-widest text-pink-500">Dog Breed</p>

        <p class="text-xl font-bold text-white sm:text-2xl"><%= breed_name %></p>

        <div class="mt-32 sm:mt-48 lg:mt-64">
          <div
            class="translate-y-8 transform opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100"
          >
            <p class="text-sm text-white">
              This is a <%= breed_name %> dog. Fetched from the Dog API using the breed name.
            </p>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>